[workspace]
members = [
    '@apqc/apqc/apqc_.ttl',
    '@apqc/apqc_aerospace_and_defence/apqc_aerospace_and_defence_.ttl',
    '@apqc/apqc_airline/apqc_airline_.ttl',
    '@apqc_cross_industry/apqc_cross_industry/apqc_cross_industry_.ttl',
    '@apqc_cross_industry/acquire_construct_and_manage_assets/apqc_cross_industry_10_.ttl',
    '@apqc_cross_industry/manage_enterprise_risk_compliance_remediation_and_resiliency/apqc_cross_industry_11_.ttl',
    '@apqc_cross_industry/manage_external_relationships/apqc_cross_industry_12_.ttl',
    '@apqc_cross_industry/develop_and_manage_business_capabilities/apqc_cross_industry_13_.ttl',
    '@apqc_cross_industry/develop_vision_and_strategy/apqc_cross_industry_1_.ttl',
    '@apqc_cross_industry/develop_and_manage_products_and_services/apqc_cross_industry_2_.ttl',
    '@apqc_cross_industry/market_and_sell_products_and_services/apqc_cross_industry_3_.ttl',
    '@apqc_cross_industry/manage_supply_chain_for_physical_products/apqc_cross_industry_4_.ttl',
    '@apqc_cross_industry/deliver_services/apqc_cross_industry_5_.ttl',
    '@apqc_cross_industry/manage_customer_service/apqc_cross_industry_6_.ttl',
    '@apqc_cross_industry/develop_and_manage_human_capital/apqc_cross_industry_7_.ttl',
    '@apqc_cross_industry/manage_information_technology_it/apqc_cross_industry_8_.ttl',
    '@apqc_cross_industry/manage_financial_resources/apqc_cross_industry_9_.ttl',
    '@fld33_domain/business_objects/business_objects_.ttl',
    '@fld33/communication/communication_.ttl',
    '@contrib/generic_innovation_interoperability/generic_innovation_interoperability.ttl',
    '@fld33/methodology/methodology_.ttl',
    '@fld33/organization/organization_.ttl',
    '@fld33/organization_communication/organization_communication_.ttl',
    '@fld33/people/people_.ttl',
    '@fld33/process/process.ttl',
    '@fld33/relations/relations_.ttl',
    '@fld33_domain/software_architecture_metric/software_architecture_metric_.ttl',
    '@fld33_domain/software_development/software_development_.ttl',
    '@fld33_domain/software_development_lifecycle/software_development_lifecycle_.ttl',
    '@fld33_domain/software_development_metric/software_development_metric_.ttl',
    '@fld33_domain/software_implementation_metric/software_implementation_metric_.ttl',
    '@fld33_domain/software_team_metric/software_team_metric_.ttl',
]
